language: node_js
node_js:
- '4'
services:
- mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: uee9UzheJIatJV3IA0QtEIq6px1Q4SGzEp+XKKc7EfZmxmCCIPVXNxOnbpXpFpGGDs1zlywVuaVcOdDeKHz52/+6teldVXDXsfw5gkLP9JlY9hjNMLefxZsbgFXLBZjH/KySYkqyvN6++X0EpicR/DTKGqwf+N3EEPpTnUhqt6yFmtwTlJMm2TOGmETqOgjmwzSBECJJyDLq+mIixnpe3MHp/2W4SSfiu12twLa3x0onAxwqGTfNkm+54B6eKumRrBtRXnnQ11Vw4yhqdR0HasCJrXfTVaqbBb3vRavnq3aZN5hY2nnxQ50XSHmFdJkFMe6j4QXBlgTeLbwtGwVzPlIyye/tYPVRCYaxsQM2Nh3ZNcRrU9hLPRA8S6mj/ur0P+NAUsJJD4sJUSx7ZScyqZ7S3fN6YFvta1QrVQlqK7ViZ20G7yeLHLV1CSNiSagDoWTTaPkyVDAMU2V3bsELZAuN4RCxI2iRsFqaMWEduOUIrlZ8EpvjvvOY3wkQLwmnAcQMt7X/M9wRmHoXT3TgmjKYZksntLh9lp1yVDXo7Sude9BGi4jIV8vjoDhyhkOU2RyIJ1fQ9eGbhFhpr9UASly4Z6gJHGZEO94IgXcK1WPRyMrBYM8f9+10DO0rwNWqvKDLouSGHgQbuhlqmrq8XEZGNisz8i2DE+68//jtW1o=
  - secure: VU1wXkyVgDlN/7qrDLG3VGJztEd2fhPciZ5qy/XUCsoX7CbtzfW9Qz+lRzHzOll/lwJn1j1rppRRiJn3HqLTV2pCyd1H/VTiBzgjUui/mKZ8xtHYdGoiHEwHc9QdXJH0czZ8cd0s2G+f8xGxhm+j0trk9tsionQOv9v88/ACLGEqoOl87bgN4BhbUdNfqxXG/WU3NLr2ITQl9CT6heWz1QmwPKEhqKLBMcwMbyMsWAAa/kUcXKIIX+IOTsuagSuwsyHVDQJCMVeayJVbII6J1e2GL/fK4D8MBvbI7U8/+EFONx9PlIy8Xeqnfl6VhnD9fOPIv349Ee1397h7S44+wGnyT/F7ArmavZ6AY538f7e8QYx/PSuprXgapccU0MZ33t0k/i9xICX10ukx2lDTxDca1pZQmLFneshkiBMqEtpo14CECaTItHzMnKU0nhS1TfkNl6pEMviL3JbLknyJfNwShzqIgKp0Pjb6wDmXsj5dg/IblHWlLlv9edlXU2m3BfhyhdZHIG6C853l7l5Qa99BFZix9jfGznrcgFzsWbftHbUD1c9CEouPh6VrqixddDZWHf/0TF2PWpiClVXnaWQE314BD2sgMwugYKT6XVqfFUJ0GGQKJ+V9cJ43aKXCNPnE78fpXY6DXCHrOoVTL1m6v3YzoROtpbdQyybciXE=
  - secure: ceF5/L+/tHWaX4bhYPsBr1z3bifUoYFoNI3P1SP8SzH/giTEJXHMSX6AMOKR0pKzKEwb9bZvS2Vo9W0gas91WGRuV7QQMM6A8tny6pu62eApA44O4fpGg+eAWQ5fzlgVrJ8A0Nwk7Yiw5nIg3FfWwgENGz4dxR5vTFz6EkREfODbCCd82rDPj8vGwn7BgsbGEfi4Orw4ejoqluO2f2E0x9QQ2C72v/qeAEwA9zBpzfQXJnlSCGHSEys0Ko2Wk4GDnDr1FbbIX+PGYVGUI82dnIsVmkoJRJUZkWbTirrRzT1ic+P6abIKMM9SWvc0HnqCX3r07gYJe2B8drUmfEL/w27ACT2zWoL1823sFhcnpxDYE8xOE2UjQPus05okV3zt+teEPCDIuqM6zxkMj8PSN8htfvlZMT9bSEKYzTCcZMODsPEIjInIsXWokREkZT1wf4xPGmLBe2ZgzRA4U8NRuxZo1cyF+KK/H+lDS7cg8TkTkgPB+4dv9b83FGV3n8t6im50lQAOXTNlSNHjRVEvJ9vuXB9f1XentyF1qsZNSwksjaOFdEiqe69bGMBIw89tMJimM6j/K2VcOgqWr7/lMzQLfsOBT2gh9BlR1LRtzdkcaEdbQ8am45A7XNpMyoyUdbkLz66cELgzXc9Y7jm6sQn/gDMzgHxH9cYm5S8o5zA=
  sudo: required
before_script: npm install
script:
- npm run test
- npm run lint
